
<?php

$imageSize= $this->getData('product_size');
$imageRenderSize=265;
$headline_tag = $this->getData('headline_tag');

$product_1 = $this->getData('product_1');
$product_2 = $this->getData('product_2');
$product_3 = $this->getData('product_3');
$product_4 = $this->getData('product_4');
$_products = array($product_1,$product_2,$product_3,$product_4);
$_products =Mage::getModel('catalog/product')->getCollection()
    ->addAttributeToFilter('sku', array('in' => $_products))
    ->addAttributeToFilter('status', 1)
    ->addAttributeToSelect('*')
    ->addUrlRewrite();
$_products_texts = array(
    $product_1 => $this->getData('product_1_text'),
    $product_2 => $this->getData('product_2_text'),
    $product_3 => $this->getData('product_3_text'),
    $product_4 => $this->getData('product_4_text')
);

?>

<?php if($this->getData('block_title')) : ?><h2><?php  echo $this->getData('block_title'); ?></h2><?php endif;?>
<div class="brandpage-product-row">
<?php foreach($_products as $_product): ?>
<div class="col-xs-6 col-sm-3 col-md-3">
    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imageRenderSize); ?>" alt="<?php echo $_product->getName();?>" title="<?php echo $_product->getName();?>" /></a>
    <h3 class="h4 text-center"><?php echo $_product->getName();?></h3>
    <?php echo $_product->getSpecialPrice(); ?>                    <?php echo $_product->getPriceHtml();
    #$product_block = new Mage_Catalog_Block_Product;

    #echo $product_block->getPriceHtml($_product);
    ?>

</div>
<?php endforeach; ?>
</div>