
<?php

$category_ids = explode(",",$this->getData('category_ids'));
$category_widget_title = $this->getData('category_widget_title');
$baseUrl = Mage::getBaseUrl();
$media_path = Mage::getBaseUrl('media');

?>

<div class="landingpage-categories">
    <h2><?php echo $category_widget_title ?></h2>
    <div class="row">
        <?php foreach($category_ids as $category_id): ?>
            <?php $category = Mage::getModel('catalog/category')->load($category_id);?>
            <div class="category">
                <a class="link" href="<?php echo $category->getUrl();?>">
                <img class="image" src="<?php echo $category->getImageUrl();?>" alt="" />
                <div class="title"><?php echo $category->getName(); ?></div>
                </a>
            </div>
        <?php endforeach;?>
    </div>
</div>
