
<?php

$category_ids = explode(",",$this->getData('category_ids'));
$category_widget_title = $this->getData('category_widget_title');
$baseUrl = Mage::getBaseUrl();
$media_path = Mage::getBaseUrl('media');

?>

<div class="landingpage-categories">
    <h2><?php echo $category_widget_title ?></h2>
    <ul class="slider">
        <?php foreach($category_ids as $category_id): ?>
            <?php $category = Mage::getModel('catalog/category')->load($category_id);?>
            <li class="slider-item">
                <img class="image" src="<?php echo $category->getImageUrl();?>" alt="" />
                <div class="title"><?php echo $category->getName(); ?></div>
                <a class="link" href="<?php echo $category->getUrl();?>"><?php echo $this->__('Category'); ?></a>
            </li>
        <?php endforeach;?>
    </ul>
</div>
