<?php

$landingpage_header_title = $this->getData('landingpage_header_title');
$landingpage_header_subtitle = $this->getData('landingpage_header_subtitle');
$landingpage_header_css = $this->getData('landingpage_header_css');

?>
<div class="landingpage-header <?php echo $landingpage_header_css; ?>">
    <?php if($landingpage_header_title) : ?>
        <h1><?php echo $landingpage_header_title ?></h1>
    <?php endif; ?>
    <?php if($landingpage_header_subtitle) : ?>
        <p><?php echo $landingpage_header_subtitle ?></p>
    <?php endif; ?>
</div>

