<?php

$title = $this->getData('headline');
$image = Mage::getBaseUrl('media').$this->getData('image');
$button_text = $this->getData('button_text');
$button_link = Mage::getBaseUrl().$this->getData('button_link');

?>
<li class="slider-item">
    <div class="title"><?php echo $title; ?></div>
    <img src="<?php echo $image; ?>" alt="<?php echo $title;?>"/>
    <a href="<?php echo $button_link;?>" class="button" ><?php echo $button_text; ?></a>
</li>

