<?php
// Webmasterei Prange Video
// class Webmasterei_Landingpage_Block_Video extends Mage_Core_Block_Abstract implements Mage_Widget_Block_Interface

?>
<?php

$platform = $this->getData('platform');
$youtube_id = $this->getData('youtube_id');
$url_mp4 = $this->getData('url_mp4');
$url_ogg = $this->getData('url_ogg');

?>
<div class="flex-video">
    <?php if ($platform == 'youtube'): ?>
        <div class="flex-video">
            <iframe width="420" height="315" src="//www.youtube.com/embed/<?php echo $youtube_id; ?>" frameborder="0"
                    allowfullscreen></iframe>
        </div>
    <?php elseif ($platform == 'selfhosted') : ?>
        <video>
            <source src="<?php echo $this->getMediaUrl() . $url_ogg ?>" type="video/ogg">
            <source src="<?php echo $this->getMediaUrl() . $url_mp4 ?>" type="video/mp4">
        </video>
    <?php endif; ?>
</div>


